project:
    type: tufte
    output-dir: docs
format:
  html:
    code-link: true
    author-meta: "Matthew Pancia"
    include-in-header: "partials/header.html"
    callout-appearance: simple
number-depth: 1
book:
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  open-graph: true
  site-url: https://mpancia.github.io/book/
  repo-url: https://github.com/mpancia/book/
  repo-branch: main
  repo-actions: [edit, issue]
  title: |
    Economics for Midwits
  author: Matthew Pancia
  date-format: MMMM, YYYY
  license: "CC BY"
  chapters:
    - index.qmd
    - book/epistemics.qmd
    - book/supply_and_demand.qmd
  appendices:
    - book/references.qmd
    - book/ack.qmd
    - book/colophon.qmd
bibliography: references.bib
bibliographystyle: apa